################################################################################
# Telemetry Stack
################################################################################
# docker stack deploy telemetry --compose-file compose.yml
################################################################################
version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    environment:
      - TZ=Europe/PariS
    ports:
      - 1883:1883
    networks:
      - telemetry-net
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/users:/mosquitto/config/users
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  influxdb:
    image: influxdb:1.7
    environment:
      - TZ=Europe/PariS
      - INFLUXDB_DB=home_db
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=224d94b90bf7f3deb335ea5f1055c3b964807ad8cd75c923595e8c94838faea1
      - INFLUXDB_USER=home_user
      - INFLUXDB_USER_PASSWORD=40fce79a5cc28273f50af15899460f58f76ebcc22ff30080813b10a42d3c5703
      - INFLUXDB_READ_USER=readme
      - INFLUXDB_READ_PASSWORD=qgezoc4o2zAyEyucX6Jz
    ports:
      - 8086:8086
    networks:
      - telemetry-net
    volumes:
      - influxdb-data:/var/lib/influxdb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  grafana:
    image: grafana/grafana:6.3.6
    environment:
      - TZ=Europe/PariS
      - GF_SECURITY_ADMIN_PASSWORD=b9ef816902af9fe509e9dd858122742ffdb0558988b503cce2cff7a1ec33cb35
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      - telemetry-net
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-log:/var/log/grafana
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  node-red:
    image: node-red-with-influx:latest
    environment:
      - TZ=Europe/PariS
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - "1880:1880"
    networks:
      - telemetry-net
    volumes:
      - node-red-data:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

volumes:
  node-red-data:
  grafana-data:
  grafana-log:
  influxdb-data:
  mosquitto-data:
  mosquitto-log:

networks:
  telemetry-net:
