################################################################################
# Telemetry Stack
################################################################################
# docker stack deploy telemetry --compose-file compose.yml
################################################################################
version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    environment:
      - TZ=Europe/Paris
    ports:
      - 1883:1883
    networks:
      - telemetry-net
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/users:/mosquitto/config/users
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.43.0
    environment:
      - TZ=Europe/Paris
    ports:
      - 8428:8428
      - 8087:8087
      - 2003:2003
      - 4242:4242
    volumes:
      - victoriametrics-data:/storage
    command:
      - '--storageDataPath=/storage'
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--influxListenAddr=:8087'
      - '--httpListenAddr=:8428'
    networks:
      - telemetry-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  influxdb:
    image: influxdb:1.8.3
    environment:
      - TZ=Europe/Paris
      - INFLUXDB_DB=home_db 
      - INFLUXDB_DATA_INDEX_VERSION=tsi1
#      - INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE=2g
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=@@INFLUXDB_ADMIN_PASSWORD@@
      - INFLUXDB_USER=home_user
      - INFLUXDB_USER_PASSWORD=@@INFLUXDB_USER_PASSWORD@@
      - INFLUXDB_READ_USER=readme
      - INFLUXDB_READ_PASSWORD=@@INFLUXDB_READ_PASSWORD@@
    ports:
      - 8086:8086
    networks:
      - telemetry-net
    volumes:
      - influxdb-data:/var/lib/influxdb
    deploy:
            # resources:
            # limits:
            # memory: 1000M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  grafana:
    image: grafana/grafana:6.3.6
    environment:
      - TZ=Europe/PariS
      - GF_SECURITY_ADMIN_PASSWORD=@@GF_SECURITY_ADMIN_PASSWORD@@
      - GF_PATHS_LOGS=/var/log/grafana/grafana.log
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      - telemetry-net
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-log:/var/log/grafana
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  node-red:
    # this image is a custom build
    # see node-red directory
    image: node-red-with-influx:latest
    environment:
      - TZ=Europe/PariS
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - "1880:1880"
    networks:
      - telemetry-net
    volumes:
      - node-red-data:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  telegraf:
    image: telegraf:1.12
    environment:
      - TZ=Europe/PariS
      - HOST_PROC=/host/proc
    depends_on:
      - influxdb
    devices:
      - /dev/vchiq
    networks:
      - telemetry-net
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/host/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

volumes:
  node-red-data:
  grafana-data:
  grafana-log:
  influxdb-data:
  mosquitto-data:
  mosquitto-log:
  victoriametrics-data:

networks:
  telemetry-net:
