################################################################################
# Telemetry Stack
################################################################################
# docker stack deploy telemetry --compose-file compose.yml
################################################################################

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    environment:
      - TZ=Europe/Paris
    ports:
      - 1883:1883
    networks:
      - telemetry-net
    volumes:
      - type: bind
        source: ./mosquitto/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
      - type: bind
        source: ./mosquitto/users
        target: /mosquitto/config/users
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

volumes:
  mosquitto-data:
  mosquitto-log:

networks:
  telemetry-net:
